
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ALPHA BEGIN BF BIBITEM CITE DEF DELIMITER END ENDITEMIZE ENVIRONMENT FRAC ITALICO_FIM ITALICO_INI ITEM ITEMIZE LABEL LEFT LINK MU NEGRITO_FIM NEGRITO_INI NEWCOMMAND NEWLINE NUM REF RIGHT RM SECTION SUBSECTION TEXT TEXTOdocumento : elementoselementos : elemento\n                 | elemento elementoselemento : titulo\n                | subtitulo\n                | paragrafo\n                | lista\n                | linktitulo : SECTIONsubtitulo : SUBSECTIONparagrafo : conteudo NEWLINEconteudo : texto\n                | texto conteudotexto : TEXT\n             | NEGRITO_INI texto NEGRITO_FIM\n             | ITALICO_INI texto ITALICO_FIMlista : ITEMIZE itens ENDITEMIZEitens : item\n             | item itensitem : ITEM conteudolink : LINK'
    
_lr_action_items = {'SECTION':([0,3,4,5,6,7,8,9,10,13,19,26,],[9,9,-4,-5,-6,-7,-8,-9,-10,-21,-11,-17,]),'SUBSECTION':([0,3,4,5,6,7,8,9,10,13,19,26,],[10,10,-4,-5,-6,-7,-8,-9,-10,-21,-11,-17,]),'ITEMIZE':([0,3,4,5,6,7,8,9,10,13,19,26,],[12,12,-4,-5,-6,-7,-8,-9,-10,-21,-11,-17,]),'LINK':([0,3,4,5,6,7,8,9,10,13,19,26,],[13,13,-4,-5,-6,-7,-8,-9,-10,-21,-11,-17,]),'TEXT':([0,3,4,5,6,7,8,9,10,13,14,15,16,17,19,22,26,29,30,],[15,15,-4,-5,-6,-7,-8,-9,-10,-21,15,-14,15,15,-11,15,-17,-15,-16,]),'NEGRITO_INI':([0,3,4,5,6,7,8,9,10,13,14,15,16,17,19,22,26,29,30,],[16,16,-4,-5,-6,-7,-8,-9,-10,-21,16,-14,16,16,-11,16,-17,-15,-16,]),'ITALICO_INI':([0,3,4,5,6,7,8,9,10,13,14,15,16,17,19,22,26,29,30,],[17,17,-4,-5,-6,-7,-8,-9,-10,-21,17,-14,17,17,-11,17,-17,-15,-16,]),'$end':([1,2,3,4,5,6,7,8,9,10,13,18,19,26,],[0,-1,-2,-4,-5,-6,-7,-8,-9,-10,-21,-3,-11,-17,]),'NEWLINE':([11,14,15,23,29,30,],[19,-12,-14,-13,-15,-16,]),'ITEM':([12,14,15,21,23,28,29,30,],[22,-12,-14,22,-13,-20,-15,-16,]),'ENDITEMIZE':([14,15,20,21,23,27,28,29,30,],[-12,-14,26,-18,-13,-19,-20,-15,-16,]),'NEGRITO_FIM':([15,24,29,30,],[-14,29,-15,-16,]),'ITALICO_FIM':([15,25,29,30,],[-14,30,-15,-16,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'documento':([0,],[1,]),'elementos':([0,3,],[2,18,]),'elemento':([0,3,],[3,3,]),'titulo':([0,3,],[4,4,]),'subtitulo':([0,3,],[5,5,]),'paragrafo':([0,3,],[6,6,]),'lista':([0,3,],[7,7,]),'link':([0,3,],[8,8,]),'conteudo':([0,3,14,22,],[11,11,23,28,]),'texto':([0,3,14,16,17,22,],[14,14,14,24,25,14,]),'itens':([12,21,],[20,27,]),'item':([12,21,],[21,21,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> documento","S'",1,None,None,None),
  ('documento -> elementos','documento',1,'p_documento','sintatico.py',7),
  ('elementos -> elemento','elementos',1,'p_elementos','sintatico.py',12),
  ('elementos -> elemento elementos','elementos',2,'p_elementos','sintatico.py',13),
  ('elemento -> titulo','elemento',1,'p_elemento','sintatico.py',20),
  ('elemento -> subtitulo','elemento',1,'p_elemento','sintatico.py',21),
  ('elemento -> paragrafo','elemento',1,'p_elemento','sintatico.py',22),
  ('elemento -> lista','elemento',1,'p_elemento','sintatico.py',23),
  ('elemento -> link','elemento',1,'p_elemento','sintatico.py',24),
  ('titulo -> SECTION','titulo',1,'p_titulo','sintatico.py',28),
  ('subtitulo -> SUBSECTION','subtitulo',1,'p_subtitulo','sintatico.py',32),
  ('paragrafo -> conteudo NEWLINE','paragrafo',2,'p_paragrafo','sintatico.py',36),
  ('conteudo -> texto','conteudo',1,'p_conteudo','sintatico.py',40),
  ('conteudo -> texto conteudo','conteudo',2,'p_conteudo','sintatico.py',41),
  ('texto -> TEXT','texto',1,'p_texto','sintatico.py',48),
  ('texto -> NEGRITO_INI texto NEGRITO_FIM','texto',3,'p_texto','sintatico.py',49),
  ('texto -> ITALICO_INI texto ITALICO_FIM','texto',3,'p_texto','sintatico.py',50),
  ('lista -> ITEMIZE itens ENDITEMIZE','lista',3,'p_lista','sintatico.py',58),
  ('itens -> item','itens',1,'p_itens','sintatico.py',62),
  ('itens -> item itens','itens',2,'p_itens','sintatico.py',63),
  ('item -> ITEM conteudo','item',2,'p_item','sintatico.py',70),
  ('link -> LINK','link',1,'p_link','sintatico.py',74),
]
